### ISSUE TITLE
Installation steps missing

### ISSUE THREAD

**Issue by haleymnatz** [FirehoseProject/foodie#1]
In the sql/seed.sql file, the lines 
```
CREATE DATABASE foodie;
```
are currently commented out. It would be helpful if the instructions were explicit to note that these steps need to either by uncommented or done manually.

**Comment by kenmazaika** [comment]
Thanks for pointing this out!  I'll try to fix this today!

**Comment by kenmazaika** [comment]
Thanks @haleymnatz!  I just made the `install.sh` explicitly run the command to create the database.  Thanks for pointing this out.
